const express= require("express");
const { dirname } = require("node:path");
const app=express();

// Serve the frontend files from the same project directory
app.use(express.static(__dirname));

// Start the server on port 3000
const PORT = process.env.PORT || 3000;

app.listen(PORT, "0.0.0.0", function () {
    console.log(`SERVER IS RUNNING ON PORT ${PORT}`);
});

// SSE endpoint used to continuously send logs to connected clients
app.get("/stream", function (req, res) {

    const clientId = req.query.clientId;

    // Configure the response for Server-Sent Events
    res.setHeader("Content-Type", "text/event-stream");
    res.setHeader("Cache-Control", "no-cache");
    res.setHeader("Connection", "keep-alive");

    // Generate and send a new log every 500 milliseconds
    const interval = setInterval(function () {

    const levels = ["INFO", "WARN", "ERROR"];
    const randomLevel = levels[Math.floor(Math.random() * levels.length)];

    const now = new Date();

    const timestamp = now.toLocaleTimeString("en-GB", {
        hour12: false
    }) + "." + String(now.getMilliseconds()).padStart(3, "0");

    const message = `[${randomLevel}] ${timestamp} -Client${clientId} : Log generated by server`;

    res.write(`data: ${message}\n\n`);

    }, 500);

    // Stop generating logs when the client disconnects
    req.on("close", function () {
    clearInterval(interval);
    });
});