const express= require("express");
const { dirname } = require("node:path");
const app=express();

app.use(express.static(__dirname));

app.listen(3000,function (){
    console.log("SERVER IS RUNNING ON PORT 3000");
});

app.get("/stream", function (req, res) {

    const clientId = req.query.clientId;

    res.setHeader("Content-Type", "text/event-stream");
    res.setHeader("Cache-Control", "no-cache");
    res.setHeader("Connection", "keep-alive");

    const interval = setInterval(function () {

    const levels = ["INFO", "WARN", "ERROR"];
    const randomLevel = levels[Math.floor(Math.random() * levels.length)];

    const now = new Date();

    const timestamp = now.toLocaleTimeString("en-GB", {
        hour12: false
    }) + "." + String(now.getMilliseconds()).padStart(3, "0");

    const message = `[${randomLevel}] ${timestamp} -Client${clientId} : Log generated by server`;

    res.write(`data: ${message}\n\n`);

    }, 500);

    req.on("close", function () {
    clearInterval(interval);
    });
});